version: "3"
services:
  app:
    container_name: nextjs
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
